import { ClerkProvider,SignIn } from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from 'next'
import { Unbounded, Open_Sans, Urbanist, Bruno_Ace } from "next/font/google";
import {Navbar} from '@/components/layout/navbar'
import { Toaster } from "@/components/ui/sonner"
import Footer from '@/components/layout/footer'
import { cn } from '@/lib/utils';

const openSans = Open_Sans({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-openSans",
});
const brunoAce = Bruno_Ace({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-brunoAce",
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
    <body className={cn(` ${brunoAce.variable} ${openSans.variable}`)}>
    {/* <SignedIn> */}
          <Navbar/>
         {children}
         <Toaster />
        {/* </SignedIn> */}
        {/* <SignedOut>
          <SignIn/>
        </SignedOut> */}
        <Footer/>
        </body>
    </html>
    </ClerkProvider>
  )
}
